import type { NextPage } from 'next';
import Head from 'next/head';
import SwitchButton from '../components/SwitchButton/SwitchButton';
import Hero from '../components/Hero/Hero';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>JuanG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <SwitchButton />
      </main>
    </div>
  );
};

export default Home;
