import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Header } from '../components/Header';

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>JuanG website</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <div>
      <Header />
    </div>
  </div>
);

export default Home;
