import { NextPage } from 'next';
import Head from 'next/head';

const Projects: NextPage = (): JSX.Element => (
  <div>
    <Head>
      <title>Projects JuanG</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>Projects</main>
  </div>
);

export default Projects;
