import { NextPage } from 'next';
import Head from 'next/head';

const Work: NextPage = (): JSX.Element => (
  <div>
    <Head>
      <title>Work JuanG</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>Work</main>
  </div>
);

export default Work;
